<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.medizininformatik-initiative</groupId>
	<artifactId>mii-processes-test-setup</artifactId>
	<version>2.0.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<name>mii-processes-test-setup</name>
	<description>Test-setup for MII process development</description>
	<url>https://github.com/medizininformatik-initiative/mii-processes-test-setup</url>

	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>manual</distribution>
		</license>
	</licenses>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.5.0</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>docker/dic1/fhir/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/dic1/bpe/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/dic2/fhir/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/dic2/bpe/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/dms/fhir/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/dms/bpe/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/hrp/fhir/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>docker/hrp/bpe/log</directory>
							<includes>
								<include>*.log.gz</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
			<plugin>
				<groupId>dev.dsf</groupId>
				<artifactId>dsf-maven-plugin</artifactId>
				<version>2.1.1-SNAPSHOT</version>
				<executions>
					<execution>
						<id>default-cli</id>
						<goals>
							<goal>generate-dev-setup-cert-files</goal>
						</goals>
						<configuration>
							<certs>
								<cert>
									<cn>Webbrowser Test User</cn>
									<email>webbrowser.test.user@invalid</email>
									<type>CLIENT</type>
									<targets>
										<target>cert/Webbrowser_Test_User.p12</target>
									</targets>
								</cert>
								<cert>
									<cn>localhost</cn>
									<sans>
										<san>dic1</san>
										<san>dic2</san>
										<san>dms</san>
										<san>hrp</san>
									</sans>
									<type>SERVER</type>
									<targets>
										<target>
											docker/secrets/localhost.chain.crt</target>
										<target>
											docker/secrets/localhost.key.plain</target>
									</targets>
								</cert>
								<cert>
									<cn>keycloak</cn>
									<sans>
										<san>localhost</san>
									</sans>
									<type>SERVER</type>
									<targets>
										<target>
											docker/secrets/keycloak.chain.crt</target>
										<target>
											docker/secrets/keycloak.key.plain</target>
									</targets>
								</cert>
								<cert>
									<cn>dic1</cn>
									<type>CLIENT</type>
									<targets>
										<target>docker/secrets/dic1.crt</target>
										<target>docker/secrets/dic1.key</target>
									</targets>
								</cert>
								<cert>
									<cn>dic2</cn>
									<type>CLIENT</type>
									<targets>
										<target>docker/secrets/dic2.crt</target>
										<target>docker/secrets/dic2.key</target>
									</targets>
								</cert>
								<cert>
									<cn>dms</cn>
									<type>CLIENT</type>
									<targets>
										<target>docker/secrets/dms.crt</target>
										<target>docker/secrets/dms.key</target>
									</targets>
								</cert>
								<cert>
									<cn>hrp</cn>
									<type>CLIENT</type>
									<targets>
										<target>docker/secrets/hrp.crt</target>
										<target>docker/secrets/hrp.key</target>
									</targets>
								</cert>
							</certs>
							<rootCa>
								<targets>
									<target>docker/secrets/root_ca.crt</target>
									<target>docker/secrets/root_ca.p12</target>
								</targets>
							</rootCa>
							<issuingCa>
								<targets>
									<target>docker/secrets/issuing_ca.crt</target>
									<target>docker/secrets/keycloak_trust_store.jks</target>
								</targets>
							</issuingCa>
							<caChain>
								<targets>
									<target>docker/secrets/ca_chain.crt</target>
								</targets>
							</caChain>
							<templates>
								<template>
									<source>src/main/resources/templates/docker.env</source>
									<target>docker/.env</target>
								</template>
							</templates>
							<keys>
								<key>
									<id>dms</id>
									<type>RSA4096</type>
									<targets>
										<target>docker/secrets/dms-data.key.plain</target>
										<target>docker/secrets/dms-data.pub</target>
									</targets>
								</key>
							</keys>
						</configuration>
						<inherited>false</inherited>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>