version: '3.8'
services:
  #dic1-fhir:
    #image: datasharingframework/fhir
  dic1-bpe:
    #image: datasharingframework/bpe
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_coordinateDataSharing|1.1,
        medizininformatik-initiativede_coordinateDataSharing|2.1,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.1,
        medizininformatik-initiativede_mergeDataSharing|2.0,
        medizininformatik-initiativede_dataReceive|1.0,
        medizininformatik-initiativede_dataReceive|1.1,
        medizininformatik-initiativede_dataReceive|2.0,
        medizininformatik-initiativede_reportReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.1,
        medizininformatik-initiativede_reportReceive|1.2,
        medizininformatik-initiativede_reportReceive|2.0

      # Report-2.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_ID: dic1-fhir-store
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_STATUS_TIMER_INTERVAL: 'PT2M'
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_HRP_IDENTIFIER: 'Test_HRP'

      # Report-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_ASYNC_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_DATALOGGINGENABLED: 'true'

      # Data-Transfer-2.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_ID: dic1-fhir-store
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BINARY_STREAM_READ_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BINARY_STREAM_READ_USE_HAPI_BLOB_STORAGE_OPERATION: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_STATUS_TIMER_INTERVAL: 'PT2M'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_PROCESS_AUTHORIZATION_ADDITIONALLY_ALLOWED_SENDERS: 'nct.dkfz.de|DIC'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_PROCESS_AUTHORIZATION_ADDITIONALLY_ALLOWED_RECEIVERS: 'nct.dkfz.de|DMS'

      # Data-Transfer-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_DATALOGGINGENABLED: 'true'

      # Data-Sharing-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BINARY_STREAM_READ_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BINARY_STREAM_READ_USE_HAPI_BLOB_STORAGE_OPERATION: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_DATALOGGINGENABLED: 'true'
  #dic2-fhir:
    # image: datasharingframework/fhir
  dic2-bpe:
    # image: datasharingframework/bpe
    secrets:
      - keycloak_trust_certificates.pem
      - keycloak_client_secret.password
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_coordinateDataSharing|1.1,
        medizininformatik-initiativede_coordinateDataSharing|2.1,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.1,
        medizininformatik-initiativede_mergeDataSharing|2.0,
        medizininformatik-initiativede_dataReceive|1.0,
        medizininformatik-initiativede_dataReceive|1.1,
        medizininformatik-initiativede_dataReceive|2.0,
        medizininformatik-initiativede_reportReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.1,
        medizininformatik-initiativede_reportReceive|1.2,
        medizininformatik-initiativede_reportReceive|2.0

      # Report-2.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_ID: dic2-fhir-store
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_STATUS_TIMER_INTERVAL: 'PT2M'
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_HRP_IDENTIFIER: 'Test_HRP'

      # Report-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_PROXY_URL: http://basic-auth-forward-proxy:8888
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_PROXY_USERNAME: proxy
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_PROXY_PASSWORD: password
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_URL: https://keycloak:8443/realms/blaze
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_ISSUER_URL: https://keycloak:8443/realms/blaze/protocol/openid-connect/token
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_TRUST_CERTIFICATES: /run/secrets/keycloak_trust_certificates.pem
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_CLIENT_ID: account
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_CLIENT_PASSWORD_FILE: /run/secrets/keycloak_client_secret.password
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_DISCOVERY_VALIDATION_LENIENT: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_PROXY_URL: http://basic-auth-forward-proxy:8888
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_PROXY_USERNAME: proxy
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_PROXY_PASSWORD: password
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_ASYNC_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_DATALOGGINGENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_PROCESS_AUTHORIZATION_ADDITIONALLY_ALLOWED_SENDERS: 'nct.dkfz.de|DIC'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_PROCESS_AUTHORIZATION_ADDITIONALLY_ALLOWED_RECEIVERS: 'nct.dkfz.de|DMS'

      # Data-Transfer-2.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_ID: dic2-fhir-store
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BINARY_STREAM_READ_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BINARY_STREAM_READ_USE_HAPI_BLOB_STORAGE_OPERATION: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_STATUS_TIMER_INTERVAL: 'PT2M'

      # Data-Transfer-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_PROXY_URL: http://basic-auth-forward-proxy:8888
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_PROXY_USERNAME: proxy
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_PROXY_PASSWORD: password
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_URL: https://keycloak:8443/realms/blaze
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_ISSUER_URL: https://keycloak:8443/realms/blaze/protocol/openid-connect/token
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_TRUST_CERTIFICATES: /run/secrets/keycloak_trust_certificates.pem
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_CLIENT_ID: account
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_CLIENT_PASSWORD_FILE: /run/secrets/keycloak_client_secret.password
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_DISCOVERY_VALIDATION_LENIENT: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_PROXY_URL: http://basic-auth-forward-proxy:8888
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_PROXY_USERNAME: proxy
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_OAUTH2_PROXY_PASSWORD: password
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_DATALOGGINGENABLED: 'true'

      # Data-Sharing-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_PROXY_URL: http://basic-auth-forward-proxy:8888
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_PROXY_USERNAME: proxy
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_PROXY_PASSWORD: password
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_URL: https://keycloak:8443/realms/blaze
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_ISSUER_URL: https://keycloak:8443/realms/blaze/protocol/openid-connect/token
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_TRUST_CERTIFICATES: /run/secrets/keycloak_trust_certificates.pem
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_CLIENT_ID: account
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_CLIENT_PASSWORD_FILE: /run/secrets/keycloak_client_secret.password
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_DISCOVERY_VALIDATION_LENIENT: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_PROXY_URL: http://basic-auth-forward-proxy:8888
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_PROXY_USERNAME: proxy
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_OAUTH2_PROXY_PASSWORD: password
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BINARY_STREAM_READ_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BINARY_STREAM_READ_USE_HAPI_BLOB_STORAGE_OPERATION: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_DATALOGGINGENABLED: 'true'

  #dms-fhir:
    #image: datasharingframework/fhir
  dms-bpe:
    #image: datasharingframework/bpe
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_coordinateDataSharing|1.1,
        medizininformatik-initiativede_coordinateDataSharing|2.0,
        medizininformatik-initiativede_executeDataSharing|1.0,
        medizininformatik-initiativede_executeDataSharing|1.1,
        medizininformatik-initiativede_executeDataSharing|2.0,
        medizininformatik-initiativede_dataSend|1.0,
        medizininformatik-initiativede_dataSend|1.1,
        medizininformatik-initiativede_dataSend|2.0

      # Data-Transfer-2.x & Data-Sharing-2.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DMS_PRIVATE_KEY: /run/secrets/dms_private_key.pem
      DE_MEDIZININFORMATIK_INITIATIVE_DMS_PUBLIC_KEY: /run/secrets/dms_public_key.pem

      # Data-Transfer-2.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_SERVER_ID: dms-fhir-store
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_SERVER_BINARY_STREAM_WRITE_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_PROCESS_AUTHORIZATION_ADDITIONALLY_ALLOWED_SENDERS: 'nct.dkfz.de|DIC'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_PROCESS_AUTHORIZATION_ADDITIONALLY_ALLOWED_RECEIVERS: 'nct.dkfz.de|DMS'

      # Data-Transfer-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_SERVER_BASE_URL: http://dms-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_DATALOGGINGENABLED: 'true'

      # Data-Sharing-1.x ENV variables
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_SERVER_BASE_URL: http://dms-fhir-store:8080/fhir
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_SERVER_BINARY_STREAM_WRITE_ENABLED: 'true'
      #DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_DATALOGGINGENABLED: 'true'

  #hrp-fhir:
    #image: datasharingframework/fhir
  hrp-bpe:
    #image: datasharingframework/bpe
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_executeDataSharing|1.0,
        medizininformatik-initiativede_executeDataSharing|1.1,
        medizininformatik-initiativede_executeDataSharing|2.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.1,
        medizininformatik-initiativede_mergeDataSharing|2.0,
        medizininformatik-initiativede_reportAutostart|1.0,
        medizininformatik-initiativede_reportAutostart|1.1,
        medizininformatik-initiativede_reportAutostart|1.2,
        medizininformatik-initiativede_reportAutostart|2.0,
        medizininformatik-initiativede_reportSend|1.0,
        medizininformatik-initiativede_reportSend|1.1,
        medizininformatik-initiativede_reportSend|1.2,
        medizininformatik-initiativede_reportSend|2.0

secrets:
  keycloak_client_secret.password:
    file: ./secrets/keycloak_client_secret.password
