version: '3.8'
services:
  dic1-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_dataReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.1,
        medizininformatik-initiativede_requestData|1.0,
        medizininformatik-initiativede_sendForm|1.0
      # DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_HRP_IDENTIFIER: 'Test_HRP'
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_DATALOGGINGENABLED: 'true'

  dic2-bpe:
    secrets:
      - keycloak_trust_certificates.pem
      - keycloak_client_secret.password
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_dataReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.1,
        medizininformatik-initiativede_sendForm|1.0
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_PROXY_URL: http://basic-auth-forward-proxy:8888
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_PROXY_USERNAME: proxy
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_PROXY_PASSWORD: password
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_ISSUER_URL: https://keycloak:8443/realms/blaze/protocol/openid-connect/token
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_TRUST_CERTIFICATES: /run/secrets/keycloak_trust_certificates.pem
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_PROXY_URL: http://basic-auth-forward-proxy:8888
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_PROXY_USERNAME: proxy
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_PROXY_PASSWORD: password
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_CLIENT_ID: account
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_OAUTH2_CLIENT_PASSWORD_FILE: /run/secrets/keycloak_client_secret.password
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_DATALOGGINGENABLED: 'true'

  dms-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_executeDataSharing|1.0,
        medizininformatik-initiativede_dataSend|1.0
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_SERVER_BASE_URL: http://dms-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_SERVER_BASE_URL: http://dms-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DMS_PRIVATE_KEY: /run/secrets/dms_private_key.pem
      DE_MEDIZININFORMATIK_INITIATIVE_DMS_PUBLIC_KEY: /run/secrets/dms_public_key.pem

  hrp-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_executeDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_reportAutostart|1.0,
        medizininformatik-initiativede_reportAutostart|1.1,
        medizininformatik-initiativede_reportSend|1.0,
        medizininformatik-initiativede_reportSend|1.1,
        medizininformatik-initiativede_extractData|1.0,
        medizininformatik-initiativede_insertForm|1.0

secrets:
  keycloak_client_secret.password:
    file: ./secrets/keycloak_client_secret.password
