version: '3.8'
services:
  dic1-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_dataReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.1,
        medizininformatik-initiativede_requestData|1.0,
        medizininformatik-initiativede_sendForm|1.0
      # DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_HRP_IDENTIFIER: 'Test_HRP'
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_OPENEDC_BASE_URL: http://dic1-imiedc:3000
      DE_MEDIZININFORMATIK_INITIATIVE_FEDC_DIC_FHIR_SERVER_BASE_URL: http://dic1-fhir-store:8080/fhir

  dic2-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_dataReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.0,
        medizininformatik-initiativede_reportReceive|1.1,
        medizininformatik-initiativede_sendForm|1.0
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_REPORT_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DIC_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_OPENEDC_BASE_URL: http://dic2-imiedc:3000
      DE_MEDIZININFORMATIK_INITIATIVE_FEDC_DIC_FHIR_SERVER_BASE_URL: http://dic2-fhir-store:8080/fhir

  dms-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_coordinateDataSharing|1.0,
        medizininformatik-initiativede_executeDataSharing|1.0,
        medizininformatik-initiativede_dataSend|1.0
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_SERVER_BASE_URL: http://dms-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_TRANSFER_DMS_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_SERVER_BASE_URL: http://dms-fhir-store:8080/fhir
      DE_MEDIZININFORMATIK_INITIATIVE_DATA_SHARING_DMS_FHIR_DATALOGGINGENABLED: 'true'
      DE_MEDIZININFORMATIK_INITIATIVE_DMS_PRIVATE_KEY: /run/secrets/dms_private_key.pem
      DE_MEDIZININFORMATIK_INITIATIVE_DMS_PUBLIC_KEY: /run/secrets/dms_public_key.pem

  hrp-bpe:
    environment:
      DEV_DSF_BPE_PROCESS_EXCLUDED: >-
        medizininformatik-initiativede_executeDataSharing|1.0,
        medizininformatik-initiativede_mergeDataSharing|1.0,
        medizininformatik-initiativede_reportAutostart|1.0,
        medizininformatik-initiativede_reportAutostart|1.1,
        medizininformatik-initiativede_reportSend|1.0,
        medizininformatik-initiativede_reportSend|1.1,
        medizininformatik-initiativede_extractData|1.0,
        medizininformatik-initiativede_insertForm|1.0
